[project]
name = "flask-bootstrap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
<<<<<<< HEAD
requires-python = ">=3.10"
=======
requires-python = ">=3.13"
>>>>>>> 71af39fccde3692cef06fd4062829399e31dba41
dependencies = [
    "flask>=3.1.2",
]
